### PR TITLE
fix: Update variables.tf to correct minor typos

### PR DESCRIPTION
**Pull request by kumar-dhanagopal**
Fixed minor typos in variables.tf

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @kumar-dhanagopal!

Can you please also run `make docker_generate_docs` to update the README with the corrected descriptions.  Thanks!

**Review by tpryan — APPROVED** [review]
LGTM

**Comment by kumar-dhanagopal** [comment]
@apeabody - I ran `make docker_generate_docs` as you requested. Besides the `README.md` file in the root directory, one other file was updated: `examples/simple_example/README.md` Please review.

**Comment by apeabody** [comment]
> @apeabody - I ran `make docker_generate_docs` as you requested. Besides the `README.md` file in the root directory, one other file was updated: `examples/simple_example/README.md` Please review.

Thanks @kumar-dhanagopal!  Looks like that second file had a stale value which also needed to be updated.

**Review by apeabody — APPROVED** [review]

**Review by apeabody — APPROVED** [review]

**Pull request merged**
